import { NextRequest } from "next/server";
import JSZip from "jszip";
import sharp from "sharp";

/**
 * Export a diagram as a VSDX (Microsoft Visio) file.
 * Creates a valid Open XML VSDX with the diagram embedded as an image
 * that Visio can open, display, and further edit.
 */
export async function POST(request: NextRequest) {
  try {
    const { svg, title } = await request.json();

    if (!svg || typeof svg !== "string") {
      return new Response(JSON.stringify({ error: "SVG content is required" }), {
        status: 400,
        headers: { "Content-Type": "application/json" },
      });
    }

    // Convert SVG to PNG for embedding
    const pngBuffer = await sharp(Buffer.from(svg), { density: 150 })
      .resize({ width: 3200, height: 2400, fit: "inside", withoutEnlargement: true })
      .png()
      .toBuffer();

    // Get image dimensions
    const metadata = await sharp(pngBuffer).metadata();
    const imgWidthPx = metadata.width || 3200;
    const imgHeightPx = metadata.height || 2400;

    // Convert pixels to Visio internal units (EMUs - English Metric Units)
    // 1 inch = 914400 EMU, at 150 DPI
    const dpi = 150;
    const imgWidthInches = imgWidthPx / dpi;
    const imgHeightInches = imgHeightPx / dpi;
    const imgWidthEmu = Math.round(imgWidthInches * 914400);
    const imgHeightEmu = Math.round(imgHeightInches * 914400);

    // Page size in inches (add margin)
    const pageWidthInches = imgWidthInches + 1;
    const pageHeightInches = imgHeightInches + 1;

    // Pin position (center of image on page)
    const pinX = pageWidthInches / 2;
    const pinY = pageHeightInches / 2;

    const diagramTitle = title || "Architecture Diagram";

    // Build VSDX ZIP structure
    const zip = new JSZip();

    // [Content_Types].xml
    zip.file("[Content_Types].xml", `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Default Extension="png" ContentType="image/png"/>
  <Override PartName="/visio/document.xml" ContentType="application/vnd.ms-visio.drawing.main+xml"/>
  <Override PartName="/visio/pages/pages.xml" ContentType="application/vnd.ms-visio.pages+xml"/>
  <Override PartName="/visio/pages/page1.xml" ContentType="application/vnd.ms-visio.page+xml"/>
  <Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/>
  <Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/>
</Types>`);

    // _rels/.rels
    zip.file("_rels/.rels", `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.microsoft.com/visio/2010/relationships/document" Target="visio/document.xml"/>
  <Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/>
  <Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties" Target="docProps/app.xml"/>
</Relationships>`);

    // docProps/core.xml
    const now = new Date().toISOString();
    zip.file("docProps/core.xml", `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <dc:title>${escapeXml(diagramTitle)}</dc:title>
  <dc:creator>DiagramAgent</dc:creator>
  <dc:description>Generated by DiagramAgent — AI-powered architecture diagram generator</dc:description>
  <dcterms:created xsi:type="dcterms:W3CDTF">${now}</dcterms:created>
  <dcterms:modified xsi:type="dcterms:W3CDTF">${now}</dcterms:modified>
</cp:coreProperties>`);

    // docProps/app.xml
    zip.file("docProps/app.xml", `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties">
  <Application>DiagramAgent</Application>
  <AppVersion>0.1</AppVersion>
</Properties>`);

    // visio/document.xml
    zip.file("visio/document.xml", `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<VisioDocument xmlns="http://schemas.microsoft.com/office/visio/2012/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
  <DocumentProperties>
    <BuildNumberCreated>0</BuildNumberCreated>
    <BuildNumberEdited>0</BuildNumberEdited>
  </DocumentProperties>
  <FaceNames>
    <FaceName ID="0" Name="Calibri" UnicodeRanges="-1 -1 0 0"/>
  </FaceNames>
  <StyleSheets>
    <StyleSheet ID="0" Name="No Style" NameU="No Style">
      <Cell N="LineWeight" V="0.01"/>
      <Cell N="LineColor" V="0"/>
      <Cell N="LinePattern" V="1"/>
      <Cell N="FillForegnd" V="1"/>
      <Cell N="FillBkgnd" V="0"/>
      <Cell N="FillPattern" V="1"/>
      <Cell N="Char.Font" V="0"/>
      <Cell N="Char.Size" V="0.1667"/>
    </StyleSheet>
  </StyleSheets>
</VisioDocument>`);

    // visio/_rels/document.xml.rels
    zip.file("visio/_rels/document.xml.rels", `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.microsoft.com/visio/2010/relationships/pages" Target="pages/pages.xml"/>
</Relationships>`);

    // visio/pages/pages.xml
    zip.file("visio/pages/pages.xml", `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Pages xmlns="http://schemas.microsoft.com/office/visio/2012/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
  <Page ID="0" Name="${escapeXml(diagramTitle)}" NameU="Page-1">
    <Rel r:id="rId1"/>
  </Page>
</Pages>`);

    // visio/pages/_rels/pages.xml.rels
    zip.file("visio/pages/_rels/pages.xml.rels", `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.microsoft.com/visio/2010/relationships/page" Target="page1.xml"/>
</Relationships>`);

    // visio/pages/_rels/page1.xml.rels — link to the image
    zip.file("visio/pages/_rels/page1.xml.rels", `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="../media/image1.png"/>
</Relationships>`);

    // visio/pages/page1.xml — the actual page with the diagram image
    zip.file("visio/pages/page1.xml", `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<PageContents xmlns="http://schemas.microsoft.com/office/visio/2012/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
  <Shapes>
    <Shape ID="1" Type="Foreign" NameU="DiagramImage" Name="${escapeXml(diagramTitle)}" UniqueID="{00000001-0000-0000-0000-000000000001}">
      <Cell N="PinX" V="${pinX}"/>
      <Cell N="PinY" V="${pinY}"/>
      <Cell N="Width" V="${imgWidthInches}"/>
      <Cell N="Height" V="${imgHeightInches}"/>
      <Cell N="LocPinX" V="${imgWidthInches / 2}"/>
      <Cell N="LocPinY" V="${imgHeightInches / 2}"/>
      <Cell N="ImgOffsetX" V="0"/>
      <Cell N="ImgOffsetY" V="0"/>
      <Cell N="ImgWidth" V="${imgWidthInches}"/>
      <Cell N="ImgHeight" V="${imgHeightInches}"/>
      <Cell N="ForeignType" V="1"/>
      <Section N="ForeignData">
        <Row>
          <Cell N="ForeignData" V=""/>
        </Row>
      </Section>
      <ForeignData ForeignType="Bitmap" CompressionType="PNG" ObjectWidth="${imgWidthEmu}" ObjectHeight="${imgHeightEmu}">
        <Rel r:id="rId1"/>
      </ForeignData>
    </Shape>
  </Shapes>
</PageContents>`);

    // visio/media/image1.png — the actual diagram image
    zip.file("visio/media/image1.png", pngBuffer);

    // Generate the VSDX file
    const vsdxBuffer = await zip.generateAsync({
      type: "nodebuffer",
      compression: "DEFLATE",
      compressionOptions: { level: 6 },
      mimeType: "application/vnd.ms-visio.drawing",
    });

    // Return the VSDX file
    return new Response(new Uint8Array(vsdxBuffer), {
      headers: {
        "Content-Type": "application/vnd.ms-visio.drawing",
        "Content-Disposition": `attachment; filename="${sanitizeFilename(diagramTitle)}.vsdx"`,
        "Content-Length": String(vsdxBuffer.length),
      },
    });
  } catch (error: any) {
    console.error("VSDX export error:", error);
    return new Response(
      JSON.stringify({ error: error.message || "Failed to export VSDX" }),
      { status: 500, headers: { "Content-Type": "application/json" } }
    );
  }
}

function escapeXml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function sanitizeFilename(str: string): string {
  return str.replace(/[^a-zA-Z0-9_\- ]/g, "").substring(0, 100) || "diagram";
}
